version: '3'

services:
  postgres:
    image: postgres:16.0-alpine
    container_name: auth-microservice-postgres
    ports:
      - 12345:5432
    environment:
      - POSTGRES_USER=userdb_user
      - POSTGRES_PASSWORD=userdb_pass
      - POSTGRES_DB=userdb

  auth-microservice:
    build:
      context: ./src/AuthService
      dockerfile: Dockerfile.development
    container_name: auth-microservice
    ports:
      - 5105:5105
      - 5106:5106
    environment:
      - ConnectionStrings__UserDatabase=Host=postgres;Port=5432;Database=userdb;Username=userdb_user;Password=userdb_pass
      - Kestrel__Endpoints__gRPC__Url=http://auth-microservice:5106
      - Kestrel__Endpoints__Http__Url=http://auth-microservice:5105
    depends_on:
      - postgres