version: '3'

services:
  postgres:
    image: postgres:16.0-alpine
    container_name: auth-microservice-postgres
    ports:
      - 12345:5432
    environment:
      - POSTGRES_USER=userdb_user
      - POSTGRES_PASSWORD=userdb_pass
      - POSTGRES_DB=userdb