version: '3'

services:
  postgres:
    image: postgres:16.0-alpine
    container_name: auth-microservice-postgres
    ports:
      - 12345:5432
    environment:
      - POSTGRES_USER=userdb_user
      - POSTGRES_PASSWORD=userdb_pass
      - POSTGRES_DB=userdb

  auth-microservice:
    build:
      context: ./src/AuthService
      dockerfile: Dockerfile.development
    container_name: auth-microservice
    ports:
      - 7000:80
    environment:
      - ConnectionStrings__UserDatabase="Host=postgres;Port=5432;Database=userdb;Username=userdb_user;Password=userdb_pass"
    depends_on:
      - postgres