apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth-microservice
  name: auth-microservice
spec:
  ports:
    - port: 5105
      protocol: TCP
      targetPort: 5105
      name: http1
    - port: 5106
      protocol: TCP
      targetPort: 5106
      name: http2
  type: LoadBalancer
  selector:
    app: auth-microservice
